try:
    print('try')
    int(123)
except ValueError:
    print('except')
else:
    print('else')
finally:
    print('finally')
